# Generated by Django 3.2 on 2021-04-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20210408_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='last_modified',
            field=models.DateTimeField(null=True),
        ),
    ]
