# Generated by Django 3.1.7 on 2021-03-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=150)),
                ('published', models.DateField(auto_now_add=True)),
                ('abstract', models.CharField(max_length=1000)),
                ('pdf', models.FileField(upload_to='books')),
            ],
        ),
    ]
