# Generated by Django 3.1.7 on 2021-04-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='NULL', upload_to=''),
            preserve_default=False,
        ),
    ]
