# Generated by Django 3.2 on 2021-04-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20210408_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='line',
            field=models.TextField(default=''),
        ),
    ]
