# Generated by Django 3.2 on 2021-05-02 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message_subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(default=7, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
