# Generated by Django 3.2 on 2021-05-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dm',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
