# Generated by Django 3.2 on 2021-05-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_dm_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dm',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
