# Generated by Django 3.2 on 2021-05-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_friend_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='dm',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
