# Generated by Django 3.2 on 2021-05-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_dm_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='dm',
            name='deleted_reciever',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dm',
            name='deleted_sender',
            field=models.BooleanField(default=False),
        ),
    ]
